apiVersion: v1
kind: Secret
metadata:
  name: booking-secret
  namespace: booking
type: Opaque
stringData:
  JWT_SECRET: thisisafakesecretchangeit
  POSTGRES_PASSWORD: postgres
  RABBITMQ_PASSWORD: guest
  RABBITMQ_DEFAULT_PASS: guest
